manifest: https://github.com/gardener/documentation/blob/docs-2.0-fix/.docforge/hugo.yaml
destination: hugo
hugo: true
hugo-structural-dirs:
- content
- static
content-files-formats:
- ".md"
- ".html"
- ".js"
- ".scss"
- ".css"
- ".toml"
- ".json"
- ".png"
- ".svg"
- ".jpg"
- ".jpeg" 
- ".gif"
resources-download-path: content/__resources
github-oauth-env-map:
  "github.com": GITHUB_OAUTH_TOKEN
markdown-enabled: true
persona-filter-enabled: true
aliases-enabled: true
docsy-edit-this-page-enabled: true
skip-link-validation: true